<?php
$country_code = array(
					"AF"=>"093", 
					"AX"=>"358", 
					"AL"=>"355",
					"DZ"=>"231",
					"AS"=>"684",
					"AD"=>"376",
					"AO"=>"244",
					"AI"=>"001",
					"AQ"=>"000",
					"AG"=>"001",
					"AR"=>"054",
					"AM"=>"374",
					"AW"=>"297",
					"AU"=>"061",
					"AT"=>"043",
					"AZ"=>"994",
					"BS"=>"001",
					"BH"=>"973",
					"BD"=>"880",
					"BB"=>"001",
					"BY"=>"375",
					"BE"=>"032",
					"BZ"=>"501",
					"BJ"=>"229",
					"BM"=>"001",
					"BT"=>"975",
					"BO"=>"591",
					"BA"=>"387",
					"BW"=>"267",
					"BV"=>"000",
					"BR"=>"055",
					"IO"=>"246",
					"VG"=>"001",
					"BN"=>"673",
					"BG"=>"359",
					"BF"=>"226",
					"BI"=>"257",
					"KH"=>"855",
					"CM"=>"237",
					"CA"=>"001",
					"CV"=>"238",
					"KY"=>"001",
					"CF"=>"236",
					"TD"=>"235",
					"CL"=>"056",
					"CN"=>"086",
					"CX"=>"061",
					"CC"=>"061",
					"CC"=>"061",
					"CO"=>"057",
					"KM"=>"269",
					"CK"=>"682",
					"CR"=>"506",
					"CI"=>"225",
					"HR"=>"385",
					"CU"=>"053",
					"CY"=>"357",
					"CZ"=>"420",
					"CD"=>"243",
					"DK"=>"045",
					"DJ"=>"253",
					"DM"=>"001",
					"DO"=>"001",
					"EC"=>"593",
					"EG"=>"020",
					"SV"=>"503",
					"GQ"=>"240",
					"ER"=>"291",
					"EE"=>"372",
					"ET"=>"251",
					"FK"=>"500",
					"FO"=>"298",
					"FJ"=>"679",
					"FI"=>"358",
					"FR"=>"033",
					"GF"=>"594",
					"PF"=>"689",
					"TF"=>"000",
					"GA"=>"241",
					"GM"=>"220",
					"GE"=>"995",
					"DE"=>"049",
					"GH"=>"233",
					"GI"=>"350",
					"GR"=>"030",
					"GL"=>"299",
					"GD"=>"001",
					"GP"=>"590",
					"GU"=>"001",
					"GT"=>"502",
					"GG"=>"000",
					"GN"=>"224",
					"GW"=>"245",
					"GY"=>"592",
					"HT"=>"509",
					"HM"=>"672",
					"HN"=>"504",
					"HK"=>"852",
					"HU"=>"036",
					"IS"=>"354",
					"IN"=>"091",
					"ID"=>"062",
					"IR"=>"098",
					"IQ"=>"964",
					"IE"=>"353",
					"IL"=>"972",
					"IT"=>"039",
					"JM"=>"001",
					"JP"=>"081",
					"JE"=>"044",
					"JO"=>"962",
					"KZ"=>"007",
					"KE"=>"254",
					"KI"=>"686",
					"KW"=>"965",
					"KG"=>"996",
					"LA"=>"856",
					"LV"=>"371",
					"LB"=>"961",
					"LS"=>"266",
					"LR"=>"231",
					"LY"=>"218",
					"LI"=>"423",
					"LT"=>"370",
					"LU"=>"352",
					"MO"=>"853",
					"MK"=>"389",
					"MG"=>"261",
					"MW"=>"265",
					"MY"=>"060",
					"MV"=>"960",
					"ML"=>"223",
					"MT"=>"356",
					"MH"=>"692",
					"MQ"=>"596",
					"MR"=>"222",
					"MU"=>"230",
					"YT"=>"269",
					"MX"=>"052",
					"FM"=>"691",
					"MD"=>"373",
					"MC"=>"377",
					"MN"=>"976",
					"ME"=>"382",
					"MS"=>"001",
					"MA"=>"212",
					"MZ"=>"258",
					"MM"=>"095",
					"NA"=>"264",
					"NR"=>"674",
					"NP"=>"977",
					"AN"=>"599",
					"NL"=>"031",
					"NC"=>"687",
					"NZ"=>"064",
					"NI"=>"505",
					"NE"=>"227",
					"NG"=>"234",
					"NU"=>"683",
					"NF"=>"672",
					"KP"=>"850",
					"MP"=>"001",
					"NO"=>"047",
					"OM"=>"968",
					"PK"=>"092",
					"PW"=>"680",
					"PS"=>"970",
					"PA"=>"507",
					"PG"=>"675",
					"PY"=>"595",
					"PE"=>"051",
					"PH"=>"063",
					"PN"=>"064",
					"PL"=>"048",
					"PT"=>"351",
					"PR"=>"001",
					"QA"=>"974",
					"CG"=>"242",
					"RE"=>"262",
					"RO"=>"040",
					"RU"=>"007",
					"RW"=>"250",
					"BL"=>"590",
					"SH"=>"290",
					"KN"=>"001",
					"LC"=>"001",
					"MF"=>"590",
					"PM"=>"508",
					"VC"=>"001",
					"WS"=>"685",
					"SM"=>"378",
					"ST"=>"239",
					"SA"=>"966",
					"SN"=>"221",
					"RS"=>"381",
					"SC"=>"248",
					"SL"=>"232",
					"SG"=>"065",
					"SK"=>"421",
					"SI"=>"386",
					"SB"=>"677",
					"SO"=>"252",
					"ZA"=>"027",
					"GS"=>"000",
					"KR"=>"082",
					"ES"=>"034",
					"LK"=>"094",
					"SD"=>"249",
					"SR"=>"597",
					"SJ"=>"047",
					"SZ"=>"268",
					"SE"=>"046",
					"CH"=>"041",
					"SY"=>"963",
					"TW"=>"886",
					"TJ"=>"992",
					"TZ"=>"255",
					"TH"=>"066",
					"TL"=>"670",
					"TG"=>"228",
					"TK"=>"690",
					"TO"=>"676",
					"TT"=>"001",
					"TN"=>"216",
					"TR"=>"090",
					"TM"=>"993",
					"TC"=>"001",
					"TV"=>"688",
					"UG"=>"256",
					"UA"=>"380",
					"AE"=>"971",
					"GB"=>"044",
					"US"=>"001",
					"VI"=>"001",
					"UY"=>"598",
					"UZ"=>"998",
					"VU"=>"678",
					"VA"=>"379",
					"VE"=>"058",
					"VN"=>"084",
					"WF"=>"681",
					"EH"=>"212",
					"YE"=>"967",
					"ZM"=>"260",
					"ZW"=>"263",
					);
                                        
                                        $country_value = $country_code[$billing_country_iso_code_2];
?>



<form action="<?php echo $action; ?>" method="post" id="paymentz_standard_checkout" name="ecom">

    <input type="hidden" name="totype" id="totype" value="<?php echo $totype;?>" />
     <input type="hidden" name="partenerid" id="partenerid" value="<?php echo $partenerid;?>" />
    <input type="hidden" name="ipaddr" id="ipaddr" value="<?php echo $ipaddr;?>" />
    <input type="hidden" name="pctype" id="pctype" value="<?php echo '1_1|1_2';?>" />
    <input type="hidden" name="description" id="description" value="<?php echo $Order_Id; ?>" />
    <input type="hidden" name="orderdescription" id="orderdescription" value="<?php echo $orderdescription; ?>"  />
    <input type="hidden" name="fromtype" id="fromtype" value="icicicredit" />
    <input type="hidden" name="paymenttype" id="paymenttype" value="" />
    <input type="hidden" name="reservedField1" id="reservedField1" value="" />
    <input type="hidden" name="reservedField2" id="reservedField2" value="" />
    <input type="hidden" name="TMPL_telnocc" id="TMPL_telnocc" value="<?php echo $country_value; ?>" />
    <input type="hidden" name="cardtype" id="cardtype" value="" />
    <input type="hidden" name="TMPL_AMOUNT" id="TMPL_AMOUNT" value="<?php echo $Amount; ?>" />
    <input type="hidden" name="TMPL_CURRENCY" id="TMPL_CURRENCY" value="<?php echo $currency_code; ?>"  />
    <input type="hidden" name="currency" id="currency" value="<?php echo $currency_code; ?>"  />
    <input type="hidden" name="key" id="key" value="<?php echo $WorkingKey; ?>" />
    <input type="hidden" name="amount" id="amount" value="<?php echo $Amount; ?>" />
    <input type="hidden" name="toid" id="toid" value="<?php echo $Merchant_Id; ?>" />
    <input type="hidden" name="redirecturl" id="redirecturl" value="<?php echo $Redirect_Url; ?>" />
    <input type="hidden" name="checksum" id="checksum" value="<?php echo $Checksum; ?>" />
    <input type="hidden" name="state" id="state" value="<?php echo $this->data['billing_cust_state']; ?>" />
    <input type="hidden" name="TMPL_city" id="TMPL_city" value="<?php echo $billing_cust_city; ?>" />
    <input type="hidden" name="TMPL_street" id="TMPL_street" value="<?php echo $billing_cust_address; ?>" />
    <input type="hidden" name="TMPL_zip" id="TMPL_zip" value="<?php echo $billing_zip_code; ?>"  />
   <input type="hidden" name="country" id="country" value="<?php echo $billing_country_iso_code_2; ?>" />
    <input type="hidden" name="phone" id="TMPL_telno" value="<?php echo $billing_cust_tel; ?>" />
    <input type="hidden" name="TMPL_emailaddr" id="TMPL_emailaddr" value="<?php echo $billing_cust_email; ?>" />


    <div class="buttons">
        <div class="right">
            <a id="button-confirm" class="button" onclick="$('#paymentz_standard_checkout').submit();">
                <span><?php echo $button_confirm; ?></span>
            </a>
        </div>
    </div></form>